version: '3.8'

services:
  # Spring Boot Application
  spring-app:
    image: my_image:v1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ipdetailsdb
    volumes:
      - pg-data:/var/lib/postgresql/data

  # Redis Cache Server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
#    volumes:
#      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/Users/suryansh.singh/SpringBoot/AdFraudDetection/bin/prometheus.yaml'

#networks:
#  default:
#    external:
#      name: custom_network

volumes:
  pg-data:
