version: '3.8'

services:
  # Spring Boot Application
  spring-app:
    image: ad_fraud_detection:v1
    ports:
      - "8080:8080"
    depends_on:
      #      - postgres-service
      #      - redis-service
      - postgres
      - redis




  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ipdetailsdb
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache Server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - '/Users/suryansh.singh/SpringBoot/AdFraudDetection/bin/prometheus.yaml:/etc/prometheus/prometheus.yml'


volumes:
  pg-data:
