#global:
#  scrape_interval: 15s

scrape_configs:
  - job_name: 'AdFraudDetection_Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8080'] # Replace with your application's address
        labels:
          application: 'AdFraudDetection'