#global:
#  scrape_interval: 15s

scrape_configs:
  - job_name: 'AdFraudDetection_Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
#      - targets: ['localhost:8080', 'localhost:9090'] # Replace with your application's address
      - targets: ['spring-app:8080', 'sping-app:9090']
        labels:
          application: 'AdFraudDetection'