apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14  # Replace with your Docker image URL
          env:
            - name: POSTGRES_USER
              value: postgres  # Set the PostgreSQL username
            - name: POSTGRES_PASSWORD
              value: postgres  # Set the PostgreSQL password
            - name: POSTGRES_DB
              value: ipdetailsdb  # Set the name of the PostgreSQL database
          ports:
            - containerPort: 5432  # The port your Spring Boot app listens on
#          imagePullPolicy: Always
#          volumeMounts:
#            - name: postgres-persistent-storage
#              mountPath: /var/lib/postgresql/data
#      volumes:
#        - name: postgres-persistent-storage
#          persistentVolumeClaim:
#            claimName: postgres-pvc  # Specify an existing PersistentVolumeClaim or create a new one

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort