apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'AdFraudDetection_Metrics'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 3s
        static_configs:
          - targets: ['spring-app-service:8080']
            labels:
              application: 'AdFraudDetection'