apiVersion: ad_fraud_detection/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2  # Set the desired number of replicas
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: suryanshsingh/ad_fraud_detection:v1  # Replace with your Docker image URL
          ports:
            - containerPort: 8080  # The port your Spring Boot app listens on
          imagePullPolicy: Always